BEGIN TRANSACTION;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "category" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"icon"	TEXT DEFAULT ' ',
	"currency"	TEXT NOT NULL,
	"isIncome"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "accounts" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"amount"	REAL NOT NULL,
	"currency"	TEXT NOT NULL,
	"type"	INTEGER NOT NULL,
	"icon"	TEXT DEFAULT ' ',
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "transactions" (
	"id"	INTEGER NOT NULL UNIQUE,
	"text"	TEXT NOT NULL,
	"amount"	REAL NOT NULL,
	"type"	INTEGER NOT NULL DEFAULT 0,
	"date"	TEXT NOT NULL,
	"category"	INTEGER NOT NULL,
	"account"	INTEGER NOT NULL,
	FOREIGN KEY("account") REFERENCES "accounts"("id") ON DELETE CASCADE,
	FOREIGN KEY("category") REFERENCES "category"("id") ON DELETE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;